version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres_container
    restart: always
    ports:
      - 5432:5432
    volumes:
      - /home/marcos/Dev/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 123
    networks:
      - python_net

  manage:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    ports:
      - 5050:80
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: marcosphip7@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123
    networks:
      - python_net

volumes:
  pgdata:

networks:
  python_net:
    driver: bridge